# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [38]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [39]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.87316865 0.4119972  0.25136095 ... 0.42482023 0.59871641 0.80709564]
 [0.53502294 0.39220273 0.39003963 ... 0.14900189 0.81636993 0.74234463]
 [0.02973915 0.71020086 0.17522673 ... 0.15924067 0.90274482 0.07649966]
 ...
 [0.85966719 0.99493545 0.16591642 ... 0.1396522  0.48234687 0.92215704]
 [0.60833534 0.37882903 0.30481384 ... 0.44792259 0.43151294 0.55425892]
 [0.55221074 0.78643197 0.45386056 ... 0.41387538 0.15657153 0.66425348]]
[[0.21519009 0.3114811  0.52353799 ... 0.82421733 0.13153592 0.78611229]
 [0.02676009 0.56395149 0.73063044 ... 0.47821339 0.90914042 0.63938277]
 [0.77445857 0.76329155 0.75555565 ... 0.96348676 0.69734154 0.80629104]
 ...
 [0.5412483  0.65600232 0.47389453 ... 0.77472635 0.09862373 0.66005662]
 [0.83557138 0.51299594 0.93762401 ... 0.58574164 0.846519   0.66829483]
 [0.80767623 0.38025536 0.84494749 ... 0.69669266 0.38304279 0.73296597]]


Без использования numpy

In [40]:
def mult(a, b):
    if len(a[0]) != len(b):
        print("Матрицы не могут быть перемножены!")
        return

    result = [[0 for i in range(len(a))] for i in range(len(a))]
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]
    return result


C использованием numpy

In [41]:
def np_mult(a, b):
    result = np.matmul(a, b)
    return result

In [42]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 702 ms, sys: 0 ns, total: 702 ms
Wall time: 704 ms


In [44]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.34 ms, sys: 964 µs, total: 2.31 ms
Wall time: 1.19 ms


In [45]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.517008740847814e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [46]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.96973823 0.1613053  0.21049094] [0.69537389 0.45148101 0.73842646]


In [47]:
def scalar_product(a,b):
    if len(a) != len(b):
          raise ValueError("Векторы должны иметь одинаковую длину")
    s = 0
    for x, y in zip(a, b):
        s += x * y
    return s

In [48]:
def np_scalar_product(a,b):
    s =  np.dot(a, b)
    return s

In [49]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 34 µs, sys: 0 ns, total: 34 µs
Wall time: 37.4 µs
CPU times: user 60 µs, sys: 0 ns, total: 60 µs
Wall time: 63.9 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** операции NumPy реализованы на языке C, что позволяет избежать общих накладных расходов, связанных с интерпретацией циклов в Python и проверкой типов объектов. Это делает вычисления с использованием NumPy гораздо более эффективными и быстрыми. Кроме того, NumPy также использует непрерывную память и векторные операции, что позволяет выполнять вычисления параллельно и дает еще больший прирост производительности.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [53]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  diagonal = np.diag(a)
  even_diag = diagonal[diagonal % 2 == 0]
  if len(even_diag) == 0:
      return 0
  else:
      return np.sum(even_diag)

In [54]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[3, 3, 7, 8, 8],
       [5, 8, 8, 9, 3],
       [2, 5, 8, 2, 8],
       [7, 6, 6, 1, 1],
       [9, 6, 7, 3, 4]])

In [55]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 152 µs, sys: 0 ns, total: 152 µs
Wall time: 159 µs


20

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [56]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    result = np.cumsum(np.array(A), axis=1) / np.arange(1, np.array(A).shape[1] + 1)
    return result

In [57]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.01476478 0.76483369 0.24094078 0.67733419 0.8073383  0.07411431
 0.64548648 0.96440979 0.74245566 0.17659844 0.18511377 0.95283162
 0.19778286 0.13789516 0.13479993 0.56843167 0.3369774  0.13367125
 0.98790182 0.61851731 0.47643573 0.12699286 0.98547551 0.76284466
 0.79394868 0.69407231 0.85815562 0.30351135 0.80580988 0.34512715
 0.50364952 0.30563198 0.87918054 0.14832147 0.78429396 0.37169534
 0.68763107 0.96211483 0.24129784 0.91307383 0.74425301 0.46751931
 0.79430161 0.02344217 0.35486942 0.57664236 0.86176951 0.67207935
 0.87727032 0.24937321 0.7509061  0.07680966 0.34621125 0.1554116
 0.8446488  0.07211954 0.90338928 0.04029962 0.0185373  0.56039492
 0.36355311 0.11279515 0.62161033 0.36791498 0.74226409 0.10058636
 0.67781103 0.51053611 0.66101338 0.23030568 0.54082082 0.05709234
 0.43521505 0.14679804 0.69528559 0.40056215 0.3327688  0.75884669
 0.0151458  0.58242905 0.3457997  0.68466381 0.96923403 0.96658347
 0.59750393 0.59541276 0.78023663 0.95126331 0.12360859 0.49019

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [58]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    groups = [list(g) for k, g in groupby(a)]
    elements = np.array([group[0] for group in groups])
    counts = np.array([len(group) for group in groups])

    return elements, counts

In [59]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 45 µs, sys: 7 µs, total: 52 µs
Wall time: 57 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [60]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    result = np.copy(X)
    result[1::2] = a
    result[::2] = result[::2] ** 3
    result = np.flip(result)
    result = np.concatenate((X, result))

    return result

In [61]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 841 µs, sys: 0 ns, total: 841 µs
Wall time: 858 µs
